'use strict';

/** Nombre de la cookie que transporta el refresh token. */
const REFRESH_COOKIE_NAME = 'ar_refresh_token';

/** Longitud del código de verificación enviado por correo. */
const VERIFICATION_CODE_LENGTH = 6;

/** Intentos fallidos antes de invalidar el código y obligar a pedir otro. */
const MAX_VERIFICATION_ATTEMPTS = 5;

/** Códigos de error estables: el frontend puede ramificar sobre ellos. */
const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  NO_BALANCE: 'NO_BALANCE',
  TEXT_TOO_LONG: 'TEXT_TOO_LONG',
  REWRITE_UNAVAILABLE: 'REWRITE_UNAVAILABLE',
  REWRITE_REFUSED: 'REWRITE_REFUSED',
  REWRITE_FAILED: 'REWRITE_FAILED',
  PAYMENT_UNAVAILABLE: 'PAYMENT_UNAVAILABLE',
  PLAN_NOT_PURCHASABLE: 'PLAN_NOT_PURCHASABLE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  LICENSE_CODE_INVALID: 'LICENSE_CODE_INVALID',
  LICENSE_CODE_USED: 'LICENSE_CODE_USED',
  LICENSE_INVALID: 'LICENSE_INVALID',
  LICENSE_REVOKED: 'LICENSE_REVOKED',
  DISCOUNT_INVALID: 'DISCOUNT_INVALID',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

const ROLES = Object.freeze({
  USER: 'USER',
  EDITOR: 'EDITOR',
  ADMIN: 'ADMIN',
});

module.exports = {
  REFRESH_COOKIE_NAME,
  VERIFICATION_CODE_LENGTH,
  MAX_VERIFICATION_ATTEMPTS,
  ERROR_CODES,
  ROLES,
};
