-- AlterTable
ALTER TABLE `licenses` ADD COLUMN `delivery` ENUM('EXECUTED', 'INSTRUCTIONS') NOT NULL DEFAULT 'EXECUTED';

-- AlterTable
ALTER TABLE `plans` ADD COLUMN `mcpDelivery` ENUM('EXECUTED', 'INSTRUCTIONS') NOT NULL DEFAULT 'EXECUTED';

